name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - run: go build -trimpath -ldflags "-w -s" -o ./foxTorrent ./cmd/foxTorrent
      - run: go test -v ./...
